### PR TITLE
Completed nodejs notes section

### LINKED ISSUE #2: To add learning notes of Nodejs (as like of JavaScript)
Node js playlist link :
https://www.youtube.com/playlist?list=PL4njvVBDLL21S6bEXRC7agpBnVPiXNbj5

### PR DESCRIPTION
**Pull request by Devendrakhatrii**
closes #2 

The content are added manually taking so much time.
- there could be a better way to optimized, feel free to do so.
- if there could be a way where we map the videos data and render it, rather than creating multiple file and just changing the title and video id.

image

### CODE REVIEW

**Comment by isarojdahal** [comment]
Right, it turns out to be lengthy one.
I haven't tried with mappings; and I don't think docusaurus has mapping solution either.
But we can create custom scripts for this.
(Below is suggested by GPT)

image

**Comment by theanupambista** [comment]
@Devendrakhatrii @isarojdahal 
It seems tedious to me as well. So i have created the script which does all the task just by giving it the youtube playlist ID.

**Comment by Devendrakhatrii** [comment]
> @Devendrakhatrii @isarojdahal It seems tedious to me as well. So i have created the script which does all the task just by giving it the youtube playlist ID.

I also wrote a script for the docker notes but there I was adding data manually and I was actually wondering about how the js notes were created.

**Comment by theanupambista** [comment]
> > @Devendrakhatrii @isarojdahal It seems tedious to me as well. So i have created the script which does all the task just by giving it the youtube playlist ID.
> 
> I also wrote a script for the docker notes but there I was adding data manually and I was actually wondering about how the js notes were created.

I had created it manually in pr #1 
In pr #12 I have included the script to generate notes automatically and all the notes created in #12 are generated using the script.

**Pull request merged**
